### ISSUE TITLE
按照步骤执行没成功 查看describe 提示 Issuing certificate as Secret does not exist

### ISSUE THREAD

**Issue by xiongpan828** [imroc/cert-manager-webhook-dnspod#21]
<img width="990" alt="image" src="https://github.com/user-attachments/assets/2cbcff22-a97f-4461-b5fb-2b5aeec6b5bd">
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/55998225-e36e-4d5c-8f3e-ed9730124470">
<img width="464" alt="image" src="https://github.com/user-attachments/assets/6cfbcbc3-47ad-4d71-a56b-7d31351026d7">

**Comment by xiongpan828** [comment]
腾讯云密钥是配置了，目前不知道哪儿错了，大佬空了看看

**Comment by xiongpan828** [comment]
<img width="2475" alt="image" src="https://github.com/user-attachments/assets/15481075-ae18-47ce-bbae-22819ce8c513">
<img width="2534" alt="image" src="https://github.com/user-attachments/assets/73488144-5bd0-4308-87dc-c60ba100996a">

**Comment by xiongpan828** [comment]
看cert-manager报错 是dns原因 解决了
启动cert-manager指定了一下dns
https://cert-manager.io/docs/configuration/acme/dns01/

感觉很奇怪 不应该

**Comment by imroc** [comment]
看起来集群里有什么特殊配置，会有 webhook 自动修改 dnsPolicy/dnsConfig之类的配置么？正常情况下应该走kube-dns，而报错里显示走的指定的 4 个 dns 地址

**Comment by xiongpan828** [comment]
这些dns好像都是dnspod的
<img width="928" alt="image" src="https://github.com/user-attachments/assets/843f902e-6a64-4c43-bede-811c3d3e8c15">

这些配置应该都没有 我直接用helm安装的
以下是我cert-manager启动配置 看看有没有帮助
<img width="873" alt="image" src="https://github.com/user-attachments/assets/2f7f27c8-b6e9-4fe8-8f01-8ecaa4496e20">

**Comment by imroc** [comment]
改了什么配置恢复的？

**Comment by xiongpan828** [comment]
启动cert-manager手动指定了一下dns服务器 最好dns服务器是dnspod自己的 114我刚才试了又有问题 看报错其他dns服务器没有缓存到设置到dnspod的_acme-challenge txt记录
https://docs.dnspod.cn/public-dns/public-dns-config-guide/
https://cert-manager.io/docs/configuration/acme/dns01/
<img width="698" alt="image" src="https://github.com/user-attachments/assets/716bc63a-e49d-487f-b3eb-764f027d4e98">

**Comment by imroc** [comment]
嗯，应该你需求特殊，需要指定 dns 服务器，一般人不需要配置这个

**Comment by xiongpan828** [comment]
应该是
