### ISSUE TITLE
ingress cert-manager.io/cluster-issuer not working

### ISSUE THREAD

**Issue by jasine** [imroc/cert-manager-webhook-dnspod#6]
ingress annotation cert-manager.io/cluster-issuer: dnspod can not create a Certificate automatically

**Comment by imroc** [comment]
You can check cert-mananger's log.

**Comment by jasine** [comment]
@imroc  logs of cert-mananger, is that relevant to cert-manager-webhook-dnspod

```
cert-manager/controller/ingress-shim "msg"="failed to determine issuer to be used for ingress resource" "error"="failed to determine issuer name to be used for ingress resource" "resource_kind"="Ingress" "resource_name"="argocd-server" "resource_namespace"="argocd" "resource_version"="v1"
```

**Comment by imroc** [comment]
Then check the log of cert-manager-webhook-dnspod. I tested it myself, it works fine

<img width="1339" alt="" src="https://user-images.githubusercontent.com/7448852/183269648-8efc35d6-e4e5-4a8e-a797-7802e5dfbd18.png">
