### ISSUE TITLE
error cleaning up challenge

### ISSUE THREAD

**Issue by IllyaTheHath** [imroc/cert-manager-webhook-dnspod#8]
Always trying to cleaning up dns challenge after generated certs, even if the dns record is successfully removed.

Logs are filled up with the follow error message: 
```E0826 09:36:38.149573       1 sync.go:282] cert-manager/challenges/finalizer "msg"="error cleaning up challenge" "error"="dnspod API call has failed: [TencentCloudSDKError] Code=ResourceNotFound.NoDataOfRecord, Message=记录列表为空。, RequestId=2781a7f8-3d0c-43e5-8b09-e07f7547b847" "dnsName"="chiyuki.studio" "resource_kind"="Challenge" "resource_name"="cert-chiyuki-studio-msfcc-3859969589-3025972435" "resource_namespace"="traefik" "resource_version"="v1" "type"="DNS-01"```

**Comment by imroc** [comment]
Maybe it's old image version, try to update the image version

**Comment by IllyaTheHath** [comment]
I'm already using the latest version(1.2.0), but it doesn't reproduce after reinstalling cert-manager and webhook using helm. I think it might related to my cert-manager config.
